### ISSUE TITLE
E02 - Gerenciamento de publicações

### ISSUE THREAD

**Issue by jschneiderm98** [Conecta-UnB/Conecta-UnB-Wiki#52]
# Gerenciamento de publicações

## Critérios de Aceitação 

- [ ] [F03 - Publicar notícias](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/10)
- [ ] [F04 - Filtrar publicações](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/13)
- [ ] [F05 - Visualizar notícias](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/11)
- [ ] [F06 - Publicar eventos](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/12)
- [ ] [F07 - Visualizar eventos](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/14)
