### ISSUE TITLE
E03 - Apresentação de recursos do campus FGA

### ISSUE THREAD

**Issue by jschneiderm98** [Conecta-UnB/Conecta-UnB-Wiki#53]
# Apresentação de recursos do campus FGA

## Critérios de Aceitação 

- [ ] [F08 - Visualizar mapa com fotos](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/15)
- [ ] [F09 - Registrar EJ/EC/Lab](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/16)
- [ ] [F10 - Visualizar dados da EJ/EC/Lab](https://github.com/Conecta-UnB/Conecta-UnB-Wiki/issues/9)
